In [2]:
from selenium.webdriver import Chrome
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait as wait
from selenium.webdriver.support.ui import Select
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException
from bs4 import BeautifulSoup
from time import sleep
from tqdm import tqdm
import urllib.request
import warnings
warnings.filterwarnings("ignore")

In [2]:
browser = Chrome('/Users/ajsaule/Desktop/chromedriver')

In [11]:
url = 'https://stat.gov.kz/official/industry/26/statistic/6'
browser.get(url)

In [12]:
lang = browser.find_element_by_xpath('//*[@id="header"]/div/div/div[3]/div[2]/ul/li[2]/button')
lang.click()

In [14]:
period = browser.find_element_by_xpath('//*[@id="selPeriodities"]')
period.click()
c_p = Select(period)
c_p.select_by_visible_text('Неделя')

In [15]:
named = browser.find_element_by_xpath('//*[@id="selNames"]')
named.click()
c_n = Select(named)
c_n.select_by_visible_text('Индекс цен и средние цены на социально-значимые продовольственные товары в Республике Казахстан')

In [16]:
import time

In [17]:
years=['2019', '2020', '2021']
for year in range(len(years)):
    sleep(8)
    p_years = browser.find_element_by_xpath('//*[@id="selPeriods"]')
    p_years.click()
    c_y = Select(p_years)
    c_y.select_by_visible_text(years[year])
    files=browser.find_elements_by_class_name('trud-archive-item')
    for file in files:
        sleep(2)
        file.click()

In [1]:
import pandas as pd
from docx import Document
import os
import time
import re
import os, shutil
from pyunpack import Archive
from rarfile import RarFile

In [47]:
pathes = ['26 mar 2014-25 apr 2017','2 may 2017 - 1 mar 2022']
def extract_rar(file):
    for path in range(len(pathes)):
        rar = RarFile('/Users/ajsaule/Desktop/parse/'+ file)
        list_1 = file.split('/')
        Archive('/Users/ajsaule/Desktop/parse/'+ file).extractall('/Users/ajsaule/Desktop/parse/'+list_1[0]+'/')

In [49]:
pathes = ['26 mar 2014-25 apr 2017','2 may 2017 - 1 mar 2022']
for path in range(len(pathes)):
    files = os.listdir('/Users/ajsaule/Desktop/parse/'+pathes[path]+'/')
    for file in files:
        if file.endswith('.rar'):
            file=pathes[path]+'/'+file
            extract_rar(file)

In [50]:
path = '/Users/ajsaule/Desktop/parse/26 mar 2014-25 apr 2017/'
files = os.listdir(path)
moveto = '/Users/ajsaule/Desktop/parse/26 mar 2014-25 apr 2017/'
files.sort()
for f in files:
    src = path+f
    dst = moveto+f
    shutil.move(src,dst)
    if not f.startswith('.'):
        if not f.endswith((".doc", ".docx", ".rar", '.DOC', '.ipynb')):
            for ff in os.listdir(path+f+'/'):
                src1=path+f+'/'+ff
                dst1 = moveto+ff
                if (len(os.listdir(path+f+'/'))==0):
                    shutil.move(src1,dst1)
                else:
                    if not ff.startswith('.'):
                        for fff in os.listdir(path+f+'/'+ff+'/'):
                            src2=path+f+'/'+ff+'/'+fff
                            dst2 = moveto+fff
                            shutil.move(src2,dst2)

In [51]:
path_2 = '/Users/ajsaule/Desktop/parse/2 may 2017 - 1 mar 2022/'
files = os.listdir(path_2)
moveto_2 = '/Users/ajsaule/Desktop/parse/2 may 2017 - 1 mar 2022/'
files.sort()
for f in files:
    src = path_2+f
    dst = moveto_2+f
    shutil.move(src,dst)
    if not f.startswith('.'):
        if not f.endswith((".doc", ".docx", ".rar", '.DOC', '.ipynb')):
            for ff in os.listdir(path_2+f+'/'):
                src1=path_2+f+'/'+ff
                dst1 = moveto_2+ff
                if (len(os.listdir(path_2+f+'/'))==0):
                    shutil.move(src1,dst1)
                else:
                    if not ff.startswith('.'):
                        for fff in os.listdir(path_2+f+'/'+ff+'/'):
                            src2=path_2+f+'/'+ff+'/'+fff
                            dst2 = moveto_2+fff
                            shutil.move(src2,dst2)

In [ ]:
def doc_to_docx(file):
    w = wc.Dispatch('Word.Application')
    doc = w.Documents.Open(basedir + '\\parse\\2 may 2017 - 1 mar 2022\\'+file)
    f_name, f_ ext = os.path.splitext(file)
    doc.SaveAs(basedir + '\\parse\\2 may 2017 - 1 mar 2022\\'+f_name+'.docx', 16)
    doc.Close(True)

In [ ]:
path = basedir + '\\parse\\2 may 2017 - 1 mar 2022\\'
files = os.listdir(path)
for file in files:
    sleep(2)
    if file.endswith(('.doc', '.DOC')):
        doc_to_docx(file)
        src = path+file
        dst = basedir+'\\move\\'+file
        shutil.move(src,dst)

In [3]:
dfs_0=[]

In [4]:
def table_read_0(document):
    document = Document("/Users/ajsaule/Desktop/parse/26 mar 2014-25 apr 2017/"+file)
    single_para = document.paragraphs[1].text
    if single_para.startswith('Об изменении цен'):
        f=f=re.findall(r'по.*года', document.paragraphs[1].text)
    else:
        f=f=re.findall(r'по.*года', document.paragraphs[4].text)
    for i in range(len(document.tables)):
        if 2<=i<=5:
            table=document.tables[i]
            data = [[cell.text for cell in row.cells] for row in table.rows]
            df = pd.DataFrame(data)
            #time.sleep(2)
            df['date']=f[0]
            dfs_0.append(pd.DataFrame(df))

In [5]:
path = '/Users/ajsaule/Desktop/parse/26 mar 2014-25 apr 2017/'
files = os.listdir(path)
for file in files:
    time.sleep(3)
    if file.endswith('.docx'):
        table_read_0(file)

KeyboardInterrupt:

In [6]:
len(dfs_0)

648

In [64]:
dfs_tmp=[]
dfs_tmp_1=[]
dfs_tmp_2=[]
dfs_tmp_3=[]

In [65]:
table_1=dfs_0[0::4]
for t1 in table_1:
    time.sleep(2)
    df_1=pd.DataFrame(t1)
    outside_col, inside_col = df_1.iloc[0], df_1.iloc[1]
    df_1.columns = pd.MultiIndex.from_tuples(list(zip(outside_col,inside_col)))
    df_1=df_1.drop(df_1.index[[0,1]]).reset_index(drop=True).drop('с начала месяца', axis=1, level=1).droplevel(level=0, axis=1).rename( columns={'':'region', 'за неделю': 'Социально-значимые продовольственные товары'})
    df_1=df_1.rename(columns={df_1.columns[8]: 'date'})
    df_1=df_1.melt(id_vars=['region', 'date'], var_name="type_of_goods", value_name="price_in_per")
    #df_1 = pd.concat()
    dfs_tmp.append(df_1)

dfs_tmp = pd.concat(dfs_tmp).reset_index().drop(columns=['index'])
time.sleep(2)
table_2=dfs_0[1::4]
for t2 in table_2:
    time.sleep(2)
    df_2=pd.DataFrame(t2)
    df_2= df_2.rename(columns=df_2.iloc[1]).drop(df_2.index[[0,1]]).reset_index(drop=True).rename( columns={'':'region'})
    df_2=df_2.rename(columns={df_2.columns[10]: 'date'})
    df_2=df_2.melt(id_vars=['region', 'date'], var_name="type_of_goods", value_name="price_in_per")
    #df_1 = pd.concat()
    dfs_tmp_1.append(df_2)

dfs_tmp_1 = pd.concat(dfs_tmp_1).reset_index().drop(columns=['index'])
time.sleep(2)
table_3=dfs_0[2::4]
for t3 in table_3:
    time.sleep(2)
    df_3=pd.DataFrame(t3)
    df_3= df_3.rename(columns=df_3.iloc[1]).drop(df_3.index[[0,1]]).reset_index(drop=True).rename( columns={'':'region'})
    df_3=df_3.rename(columns={df_3.columns[11]: 'date'})
    df_3=df_3.melt(id_vars=['region', 'date'], var_name="type_of_goods", value_name="price_in_per")
    #df_1 = pd.concat()
    dfs_tmp_2.append(df_3)

dfs_tmp_2 = pd.concat(dfs_tmp_2).reset_index().drop(columns=['index'])
time.sleep(2)
table_4=dfs_0[3::4]
for t4 in table_4:
    time.sleep(3)
    df_4=pd.DataFrame(t4)
    df_4= df_4.rename(columns=df_4.iloc[1]).drop(df_4.index[[0,1]]).reset_index(drop=True).rename( columns={'':'region'})
    df_4=df_4.rename(columns={df_4.columns[10]: 'date'})
    df_4=df_4.melt(id_vars=['region', 'date'], var_name="type_of_goods", value_name="price_in_per")
    #df_1 = pd.concat()
    dfs_tmp_3.append(df_4)

dfs_tmp_3 = pd.concat(dfs_tmp_3).reset_index().drop(columns=['index'])
sleep(2)

In [71]:
l_pd=[dfs_tmp, dfs_tmp_1, dfs_tmp_2, dfs_tmp_3]
n_df_0=pd.concat(l_pd)

In [72]:
n_df_0

,region,date,type_of_goods,price_in_per
0,Астана,по 29 марта 2016 года,Социально-значимые продовольственные товары,"99,9"
1,Алматы,по 29 марта 2016 года,Социально-значимые продовольственные товары,"100,7"
2,Актау,по 29 марта 2016 года,Социально-значимые продовольственные товары,"100,0"
3,Актобе,по 29 марта 2016 года,Социально-значимые продовольственные товары,"100,1"
4,Атырау,по 29 марта 2016 года,Социально-значимые продовольственные товары,"100,0"
...,...,...,...,...
27697,Семей,по 30 июня 2015 года,соль,"100,0"
27698,Талдыкорган,по 30 июня 2015 года,соль,"100,0"
27699,Тараз,по 30 июня 2015 года,соль,"100,0"
27700,Шымкент,по 30 июня 2015 года,соль,"100,0"
27701,По обследованным городам,по 30 июня 2015 года,соль,"100,0"

In [74]:
dfs=[]

In [75]:
def table_read(document):
    document = Document("/Users/ajsaule/Desktop/parse/2 may 2017 - 1 mar 2022/"+file)
    f=re.findall(r'по.*года', document.paragraphs[1].text)
    for i in range(len(document.tables)):
        if 2<=i<=4:
            table=document.tables[i]
            data = [[cell.text for cell in row.cells] for row in table.rows]
            df = pd.DataFrame(data)
            df['date']=f[0]
            dfs.append(pd.DataFrame(df))

In [76]:
path ='/Users/ajsaule/Desktop/parse/2 may 2017 - 1 mar 2022/'
files = os.listdir(path)
for file in files:
    time.sleep(3)
    if file.endswith('.docx'):
        table_read(file)

In [80]:
len(dfs)

762

In [156]:
dfs[0]

                              Социально-значимые продовольственные товары  \
                                                                за неделю
0                             Социально-значимые продовольственные товары
1                                                               за неделю
2                 Нур-Султан                                        100,3
3                     Алматы                                         99,4
4                    Шымкент                                        100,6
5                      Актау                                        100,4
6                     Актобе                                        100,9
7                     Атырау                                        100,7
8                  Жезказган                                        100,1
9                   Кокшетау                                        100,3
10                 Караганда                                        101,5
11                  Костанай                                        100,9
12                 Кызылорда                                        100,7
13                   Уральск                                         99,5
14          Усть-Каменогорск                                        100,4
15                  Павлодар                                        100,2
16             Петропавловск                                        100,1
17                     Семей                                        100,5
18               Талдыкорган                                        101,1
19                     Тараз                                        100,5
20                 Туркестан                                        100,4
21  По обследованным городам                                        100,4

                                                 \
                                с начала месяца
0   Социально-значимые продовольственные товары
1                               с начала месяца
2                                         100,8
3                                          99,9
4                                         101,4
5                                         101,9
6                                         102,4
7                                         102,0
8                                         102,6
9                                         100,8
10                                        102,9
11                                        101,6
12                                        102,9
13                                        100,0
14                                        100,7
15                                        100,2
16                                        100,6
17                                        101,0
18                                        101,6
19                                        101,3
20                                        101,5
21                                        101,1

    Мука пшеничная  первого сорта  Хлеб пшеничный из муки первого сорта   \
    Мука пшеничная  первого сорта  Хлеб пшеничный из муки первого сорта
0   Мука пшеничная  первого сорта  Хлеб пшеничный из муки первого сорта
1   Мука пшеничная  первого сорта  Хлеб пшеничный из муки первого сорта
2                           100,0                                   97,3
3                            99,5                                  100,0
4                           100,0                                  100,0
5                           100,0                                  100,0
6                           100,0                                  100,0
7                            ...*                                  100,0
8                           100,0                                  100,0
9                           100,0                                   91,9
10                          100,0                                  100,0
11                          100,0                                  100,0
12                          100,0                                  100,0
13                           ...*                                  100,0
14                          101,4                                  100,0
15                          100,0                                  100,0
16                          101,6                                  100,0
17                          101,4                                  100,0
18                          100,0                                  100,0
19                          100,0                                  100,0
20                           ...*                                  100,0
21                          100,1                                   99,4

    Рожки   Рис   Крупа гречневая  по 14 апреля 2020 года
    Рожки   Рис   Крупа гречневая  по 14 апреля 2020 года
0   Рожки   Рис   Крупа гречневая  по 14 апреля 2020 года
1   Рожки   Рис   Крупа гречневая  по 14 апреля 2020 года
2   100,0  101,6            102,0  по 14 апреля 2020 года
3   100,0  100,0             99,1  по 14 апреля 2020 года
4   105,1  102,6             92,5  по 14 апреля 2020 года
5     ...   96,8            100,0  по 14 апреля 2020 года
6   100,0  100,0            100,0  по 14 апреля 2020 года
7   100,0  100,0            102,9  по 14 апреля 2020 года
8   100,0  100,0            100,0  по 14 апреля 2020 года
9   100,0  100,0            100,0  по 14 апреля 2020 года
10  100,0  100,0            110,1  по 14 апреля 2020 года
11  100,0  100,0            100,0  по 14 апреля 2020 года
12  100,0   96,8            100,0  по 14 апреля 2020 года
13  100,0   96,0            103,2  по 14 апреля 2020 года
14  101,5  100,0            101,0  по 14 апреля 2020 года
15  100,0   99,3            100,0  по 14 апреля 2020 года
16  100,0  100,0            101,2  по 14 апреля 2020 года
17  101,0  100,0            100,7  по 14 апреля 2020 года
18  100,0  100,0            103,5  по 14 апреля 2020 года
19  100,0  100,0            100,0  по 14 апреля 2020 года
20  100,0   98,6            103,4  по 14 апреля 2020 года
21  100,4   99,8            101,1  по 14 апреля 2020 года

In [81]:
dfs_temp=[]
dfs_temp_1=[]
dfs_temp_2=[]

In [82]:
table_1=dfs[0::3]
for t1 in table_1:
    time.sleep(2)
    df_1=pd.DataFrame(t1)
    outside_col, inside_col = df_1.iloc[0], df_1.iloc[1]
    df_1.columns = pd.MultiIndex.from_tuples(list(zip(outside_col,inside_col)))
    df_1=df_1.drop(df_1.index[[0,1]]).reset_index(drop=True).drop('с начала месяца', axis=1, level=1).droplevel(level=1, axis=1).rename( columns={'':'region'})
    df_1=df_1.rename(columns={df_1.columns[7]: 'date'})
    df_1=df_1.melt(id_vars=['region', 'date'], var_name="type_of_goods", value_name="price_in_per")
    #df_1 = pd.concat()
    dfs_temp.append(df_1)

dfs_temp = pd.concat(dfs_temp).reset_index().drop(columns=['index'])
time.sleep(2)
table_2=dfs[1::3]
for t2 in table_2:
    time.sleep(3)
    df_2=pd.DataFrame(t2)
    df_2= df_2.rename(columns=df_2.iloc[0]).drop(df_2.index[0]).reset_index(drop=True).rename( columns={'':'region'})
    df_2=df_2.rename(columns={df_2.columns[8]: 'date'})
    df_2=df_2.melt(id_vars=['region', 'date'], var_name="type_of_goods", value_name="price_in_per")
    #df_1 = pd.concat()
    dfs_temp_1.append(df_2)

dfs_temp_1 = pd.concat(dfs_temp_1).reset_index().drop(columns=['index'])
time.sleep(2)
table_3=dfs[2::3]
for t3 in table_3:
    time.sleep(3)
    df_3=pd.DataFrame(t3)
    df_3= df_3.rename(columns=df_3.iloc[0]).drop(df_3.index[0]).reset_index(drop=True).rename( columns={'':'region'})
    df_3=df_3.rename(columns={df_3.columns[8]: 'date'})
    df_3=df_3.melt(id_vars=['region', 'date'], var_name="type_of_goods", value_name="price_in_per")
    #df_1 = pd.concat()
    dfs_temp_2.append(df_3)

dfs_temp_2 = pd.concat(dfs_temp_2).reset_index().drop(columns=['index'])
time.sleep(2)

In [165]:
dfs_temp[60:80]

,region,date,type_of_goods,price_in_per
60,Нур-Султан,по 14 апреля 2020 года,Рожки,"100,0"
61,Алматы,по 14 апреля 2020 года,Рожки,"100,0"
62,Шымкент,по 14 апреля 2020 года,Рожки,"105,1"
63,Актау,по 14 апреля 2020 года,Рожки,...
64,Актобе,по 14 апреля 2020 года,Рожки,"100,0"
65,Атырау,по 14 апреля 2020 года,Рожки,"100,0"
66,Жезказган,по 14 апреля 2020 года,Рожки,"100,0"
67,Кокшетау,по 14 апреля 2020 года,Рожки,"100,0"
68,Караганда,по 14 апреля 2020 года,Рожки,"100,0"
69,Костанай,по 14 апреля 2020 года,Рожки,"100,0"
70,Кызылорда,по 14 апреля 2020 года,Рожки,"100,0"
71,Уральск,по 14 апреля 2020 года,Рожки,"100,0"
72,Усть-Каменогорск,по 14 апреля 2020 года,Рожки,"101,5"
73,Павлодар,по 14 апреля 2020 года,Рожки,"100,0"
74,Петропавловск,по 14 апреля 2020 года,Рожки,"100,0"
75,Семей,по 14 апреля 2020 года,Рожки,"101,0"
76,Талдыкорган,по 14 апреля 2020 года,Рожки,"100,0"
77,Тараз,по 14 апреля 2020 года,Рожки,"100,0"
78,Туркестан,по 14 апреля 2020 года,Рожки,"100,0"
79,По обследованным городам,по 14 апреля 2020 года,Рожки,"100,4"

In [83]:
l_pd_2=[dfs_temp, dfs_temp_1, dfs_temp_2]
n_df=pd.concat(l_pd_2)

In [84]:
n_df

,region,date,type_of_goods,price_in_per
0,Нур-Султан,по 14 апреля 2020 года,Социально-значимые продовольственные товары,"100,3"
1,Алматы,по 14 апреля 2020 года,Социально-значимые продовольственные товары,"99,4"
2,Шымкент,по 14 апреля 2020 года,Социально-значимые продовольственные товары,"100,6"
3,Актау,по 14 апреля 2020 года,Социально-значимые продовольственные товары,"100,4"
4,Актобе,по 14 апреля 2020 года,Социально-значимые продовольственные товары,"100,9"
...,...,...,...,...
35121,Семей,по 13 марта 2018 года,Соль,"96,5"
35122,Талдыкорган,по 13 марта 2018 года,Соль,"100,0"
35123,Тараз,по 13 марта 2018 года,Соль,"100,0"
35124,Шымкент,по 13 марта 2018 года,Соль,"100,0"
35125,По обследованным городам,по 13 марта 2018 года,Соль,"100,1"

In [87]:
dfs_1=[]

In [88]:
def table_read_1(document):
    document = Document("/Users/ajsaule/Desktop/parse/9-15 mar 2022/"+file)
    f=re.findall(r'по.*года', document.paragraphs[1].text)
    for i in range(len(document.tables)):
        if 8<=i<=10:
            table=document.tables[i]
            data = [[cell.text for cell in row.cells] for row in table.rows]
            df = pd.DataFrame(data)
            df['date']=f[0]
            dfs_1.append(pd.DataFrame(df))

In [89]:
path ='/Users/ajsaule/Desktop/parse/9-15 mar 2022/'
files = os.listdir(path)
for file in files:
    #time.sleep(3)
    if file.endswith('.docx'):
        table_read_1(file)

In [93]:
dfs_temp_3=[]
dfs_temp_4=[]
dfs_temp_5=[]

In [94]:
table_1=dfs_1[0::3]
for idx,t1 in enumerate(table_1):
    df_1=pd.DataFrame(t1)
    if idx==0:
        df_1= df_1.rename(columns=df_1.iloc[0]).drop(df_1.index[0]).reset_index(drop=True).rename( columns={'':'region'})
        df_1=df_1.rename(columns={df_1.columns[7]: 'date'})
        df_1=df_1.melt(id_vars=['region', 'date'], var_name="type_of_goods", value_name="price_in_per")
    elif idx==1:
        outside_col, inside_col = df_1.iloc[0], df_1.iloc[1]
        df_1.columns = pd.MultiIndex.from_tuples(list(zip(outside_col,inside_col)))
        df_1=df_1.drop(df_1.index[[0,1]]).reset_index(drop=True).drop('с начала месяца', axis=1, level=1).droplevel(level=1, axis=1).rename( columns={'':'region'})
        df_1=df_1.rename(columns={df_1.columns[7]: 'date'})
        df_1=df_1.melt(id_vars=['region', 'date'], var_name="type_of_goods", value_name="price_in_per")
    dfs_temp_3.append(df_1)

#time.sleep(3)
dfs_temp_3 = pd.concat(dfs_temp_3).reset_index().drop(columns=['index'])
table_2=dfs_1[1::3]
for t2 in table_2:
    time.sleep(2)
    df_2=pd.DataFrame(t2)
    df_2= df_2.rename(columns=df_2.iloc[0]).drop(df_2.index[0]).reset_index(drop=True).rename( columns={'':'region'})
    df_2=df_2.rename(columns={df_2.columns[8]: 'date'})
    df_2=df_2.melt(id_vars=['region', 'date'], var_name="type_of_goods", value_name="price_in_per")
    #df_1 = pd.concat()
    dfs_temp_4.append(df_2)

dfs_temp_4 = pd.concat(dfs_temp_4).reset_index().drop(columns=['index'])

table_3=dfs_1[2::3]
for t3 in table_3:
    time.sleep(2)
    df_3=pd.DataFrame(t3)
    df_3= df_3.rename(columns=df_3.iloc[0]).drop(df_3.index[0]).reset_index(drop=True).rename( columns={'':'region'})
    df_3=df_3.rename(columns={df_3.columns[8]: 'date'})
    df_3=df_3.melt(id_vars=['region', 'date'], var_name="type_of_goods", value_name="price_in_per")
    #df_1 = pd.concat()
    dfs_temp_5.append(df_3)

dfs_temp_5 = pd.concat(dfs_temp_5).reset_index().drop(columns=['index'])
time.sleep(2)

In [95]:
l_pd_3=[dfs_temp_3, dfs_temp_4, dfs_temp_5]
n_df_1=pd.concat(l_pd_3)

In [96]:
n_df_1

,region,date,type_of_goods,price_in_per
0,По обследованным городам,по состоянию на 15 марта 2022 года,Социально-значимые продовольственные товары,"105,6"
1,Нур-Султан,по состоянию на 15 марта 2022 года,Социально-значимые продовольственные товары,"106,2"
2,Алматы,по состоянию на 15 марта 2022 года,Социально-значимые продовольственные товары,"104,5"
3,Шымкент,по состоянию на 15 марта 2022 года,Социально-значимые продовольственные товары,"105,0"
4,Актау,по состоянию на 15 марта 2022 года,Социально-значимые продовольственные товары,"105,9"
...,...,...,...,...
275,Семей,по состоянию на 9 марта 2022 года,Соль,"100,0"
276,Талдыкорган,по состоянию на 9 марта 2022 года,Соль,"100,0"
277,Тараз,по состоянию на 9 марта 2022 года,Соль,"100,0"
278,Туркестан,по состоянию на 9 марта 2022 года,Соль,"100,0"
279,По обследованным городам,по состоянию на 9 марта 2022 года,Соль,"100,1"

In [101]:
dfs_2=[]

In [102]:
def table_read_2(document):
    document = Document("/Users/ajsaule/Desktop/parse/24 mar-17 may 2022/"+file)
    f=re.findall(r'по.*года', document.paragraphs[1].text)
    for i in range(len(document.tables)):
        if i==4:
            table=document.tables[i]
            data = [[cell.text for cell in row.cells] for row in table.rows]
            df = pd.DataFrame(data)
            df['date']=f[0]
            #df.date = df.date.str.replace('по состоянию на ','').copy()
            dfs_2.append(pd.DataFrame(df))

In [103]:
path ='/Users/ajsaule/Desktop/parse/24 mar-17 may 2022/'
files = os.listdir(path)
for file in files:
    time.sleep(2)
    if file.endswith('.docx'):
        table_read_2(file)

In [104]:
dfs_2= pd.concat(dfs_2).reset_index().drop(columns=['index'])
time.sleep(2)
dfs_2= dfs_2.rename(columns=dfs_2.iloc[0]).drop(dfs_2.index[0]).reset_index(drop=True)
time.sleep(2)
dfs_2=dfs_2.rename(columns={dfs_2.columns[21]: 'date', dfs_2.columns[0]: 'type_of_goods'})
time.sleep(2)
dfs_2=dfs_2.melt(id_vars=['type_of_goods', 'date'], var_name="region", value_name="price_in_per")

In [105]:
dfs_2

,type_of_goods,date,region,price_in_per
0,Социально-значимые продовольственные товары,по состоянию на 29 марта 2022 года,По обследованным городам,"101,3"
1,Мука пшеничная первого сорта,по состоянию на 29 марта 2022 года,По обследованным городам,"101,2"
2,Хлеб пшеничный из муки первого сорта,по состоянию на 29 марта 2022 года,По обследованным городам,"100,6"
3,Рожки (весовые),по состоянию на 29 марта 2022 года,По обследованным городам,"100,9"
4,"Рис шлифованный, полированный (весовой)",по состоянию на 29 марта 2022 года,По обследованным городам,"100,6"
...,...,...,...,...
3755,Лук репчатый,по состоянию на 3 мая 2022 года,Туркестан,"105,2"
3756,Капуста белокочанная,по состоянию на 3 мая 2022 года,Туркестан,"84,9"
3757,Сахар-песок,по состоянию на 3 мая 2022 года,Туркестан,"102,4"
3758,"Яйца, 1 категории",по состоянию на 3 мая 2022 года,Туркестан,"99,0"
3759,Соль,по состоянию на 3 мая 2022 года,Туркестан,"100,0"

In [133]:
pdList = [n_df_0, n_df, n_df_1, dfs_2]
final_table= pd.concat(pdList).reset_index().drop(columns=['index'])

In [148]:
final_table

,region,date,type_of_goods,price_in_per
0,Нур-Султан,2016-03-29,Социальнозначимые продовольственные товары,"99,9"
1,Алматы,2016-03-29,Социальнозначимые продовольственные товары,"100,7"
2,Актау,2016-03-29,Социальнозначимые продовольственные товары,"100,0"
3,Актобе,2016-03-29,Социальнозначимые продовольственные товары,"100,1"
4,Атырау,2016-03-29,Социальнозначимые продовольственные товары,"100,0"
...,...,...,...,...
212651,Туркестан,2022-05-03,Лук репчатый,"105,2"
212652,Туркестан,2022-05-03,Капуста белокочанная,"84,9"
212653,Туркестан,2022-05-03,Сахар-песок,"102,4"
212654,Туркестан,2022-05-03,"Яйца, 1 категория","99,0"
212655,Туркестан,2022-05-03,Соль,"100,0"

In [135]:
final_table['type_of_goods'] =  final_table['type_of_goods'].apply(lambda x: x.replace('(','').replace(')',''))

In [145]:
final_table.type_of_goods = final_table.type_of_goods.str.capitalize()

In [15]:
replaces = {'января': '01', 'февраля':'02', 'марта':'03', 'апреля':'04', 'мая':'05', 'июня':'06', 
          'июля':'07','августа':'08', 'сентября':'09', 'октября':'10', 'ноября':'11', 'декабря':'12',
            ' года':'', 'по состоянию на ': '', 'по ':'', '\n':'', '-':'', 'Капустабелокочанная':'Капуста белокочанная',
           '1': ' I', 'категории':'категория', 'Мука пшеничная  первого сорта': 'Мука пшеничная первого сорта', 
           ' весовая':'','шлифованный, полированный весовой':'', ' весовые':'', 'сорта ':'сорта', 'Сахарпесок':'Сахар-песок',
           'cахарпесок':'Сахар-песок','Сахарпесок':'Сахар-песок', 'Рис ':'Рис', 'Астана': 'Нур-Султан', 'НурСултан': 'Нур-Султан'}

In [18]:
def check_goods(x):
    if x == 'Яйца':
        return 'Яйца, I категории'
    if x.find('Яйца') != -1:
        return 'Яйца, I категории'
    if x=='Мука пшеничная':
        return 'Мука пшеничная из высшего сорта'
    else:
        return x

final_table.type_of_goods = final_table.type_of_goods.apply(lambda x: check_goods(x))

In [16]:
for key, value in replaces.items():
    #final_table.date = final_table.date.str.replace(key, value)
    final_table.region = final_table.region.str.replace(key, value)
    final_table.type_of_goods = final_table.type_of_goods.str.replace(key, value)

In [147]:
final_table['date'] =  pd.to_datetime(final_table['date'], format='%d %m %Y')

In [20]:
final_table['type_of_goods'].unique()

array(['Социальнозначимые продовольственные товары',
       'Мука пшеничная первого сорта',
       'Хлеб пшеничный из муки первого сорта', 'Рис', 'Вермишель',
       'Лапша', 'Рожки', 'Гречневая', 'Овсяная', 'Манная', 'Перловая',
       'Пшено', 'Масло подсолнечное', 'Масло сливочное несоленое',
       'Масло растительносливочное спрэд',
       'Говядина лопаточногрудная часть', 'Баранина с костями', 'Куры',
       'Окорочка куриные', 'Молоко пастеризованное 2,5%',
       'Молоко пастеризованное 3,2%', 'Кефир 2,5%', 'Кефир 3,2%',
       'Творог', 'Сыры сычужные', 'Картофель', 'Морковь', 'Лук репчатый',
       'Капуста белокочанная', 'Свекла', 'Сахар-песок',
       'Чай черный гранулированный', 'Яйца, I категории', 'Соль',
       'Крупа гречневая',
       'Мясо кур бедренная и берцовая кость с прилегающей к ней мякотью',
       '\xa0'], dtype=object)

In [19]:
final_table.groupby('type_of_goods').first()

,region,date,price_in_per
type_of_goods,,,
,По обследованным городам,2022-03-24,По обследованным городам
Баранина с костями,Нур-Султан,2016-03-29,"100,0"
Вермишель,Нур-Султан,2016-03-29,"100,0"
Говядина лопаточногрудная часть,Нур-Султан,2016-03-29,"100,0"
Гречневая,Нур-Султан,2016-03-29,"100,0"
Капуста белокочанная,Нур-Султан,2016-03-29,"100,0"
Картофель,Нур-Султан,2016-03-29,"100,0"
"Кефир 2,5%",Нур-Султан,2016-03-29,"100,0"
"Кефир 3,2%",Нур-Султан,2016-03-29,"100,0"
Крупа гречневая,Нур-Султан,2020-04-14,"102,0"
Куры,Нур-Султан,2016-03-29,"100,0"
Лапша,Нур-Султан,2016-03-29,"100,0"
Лук репчатый,Нур-Султан,2016-03-29,"97,1"
Манная,Нур-Султан,2016-03-29,"100,0"
Масло подсолнечное,Нур-Султан,2016-03-29,"100,0"
Масло растительносливочное спрэд,Нур-Султан,2016-03-29,"100,0"
Масло сливочное несоленое,Нур-Султан,2016-03-29,"100,5"
"Молоко пастеризованное 2,5%",Нур-Султан,2016-03-29,"100,0"
"Молоко пастеризованное 3,2%",Нур-Султан,2016-03-29,"100,0"
Морковь,Нур-Султан,2016-03-29,"100,0"
Мука пшеничная первого сорта,Нур-Султан,2016-03-29,"100,0"
Мясо кур бедренная и берцовая кость с прилегающей к ней мякотью,Нур-Султан,2020-04-14,"101,3"
Овсяная,Нур-Султан,2016-03-29,"100,0"
Окорочка куриные,Нур-Султан,2016-03-29,"100,0"
Перловая,Нур-Султан,2016-03-29,"100,0"
Пшено,Нур-Султан,2016-03-29,"100,0"
Рис,Нур-Султан,2016-03-29,"100,0"
Рожки,Нур-Султан,2016-03-29,"100,0"
Сахар-песок,Нур-Султан,2016-03-29,"100,0"
Свекла,Нур-Султан,2016-03-29,"100,8"
Соль,Нур-Султан,2016-03-29,"100,0"
Социальнозначимые продовольственные товары,Нур-Султан,2016-03-29,"99,9"
Сыры сычужные,Нур-Султан,2016-03-29,"100,0"
Творог,Нур-Султан,2016-03-29,"100,8"
Хлеб пшеничный из муки первого сорта,Нур-Султан,2016-03-29,"100,0"
Чай черный гранулированный,Нур-Султан,2016-03-29,"100,0"
"Яйца, I категории",Нур-Султан,2016-03-29,"99,7"

In [21]:
final_table.to_csv('/Users/ajsaule/Desktop/script/table.csv')